import pyautogui as py 
py.press("win")
py.write("chrome")
py.press("enter")
py.sleep(2)
py.write("senai americana")
py.press("enter")
py.sleep(2)
py.click(270,465)
py.sleep(3)
py.click(1531,761)
py.sleep(2)
py.click(248,495)
py.sleep(2)
py.write("python")
py.sleep(2)
py.press("enter")
py.vscroll(-600)